[build]
  # Confirma el comando de construcci√≥n y la carpeta de salida
  command = "npm run build"
  publish = "dist/come-ya/browser" 

[[redirects]]
  # Redirige todas las rutas al archivo index.html
  from = "/*"
  to = "/index.html"
  status = 200
  force = true